[tool.poetry]
name = "game"
# Don't change version here. See Makefile
version = "0.0.0"
description = "Game"
authors = ["me"]

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.3"
pre-commit = "^3.5.0"
isort = "^5.12.0"
black = "^23.10.1"
flake8 = "^6.1.0"
